# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/design3.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PaletaDeCores(object):
    def setupUi(self, PaletaDeCores):
        PaletaDeCores.setObjectName("PaletaDeCores")
        PaletaDeCores.resize(820, 662)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("design/imgs/brush.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PaletaDeCores.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(PaletaDeCores)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QtWidgets.QFrame(self.centralwidget)
        self.header.setMaximumSize(QtCore.QSize(16777215, 55))
        self.header.setStyleSheet("background-color: #f8f8ff")
        self.header.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header.setObjectName("header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.header)
        self.frame.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.headerTitle = QtWidgets.QTextBrowser(self.frame)
        self.headerTitle.setGeometry(QtCore.QRect(90, 5, 271, 71))
        self.headerTitle.setStyleSheet("QTextBrowser {\n"
"font-family: \'Roboto\', sans-serif;\n"
"color: #484349;\n"
"font-size: 35px;\n"
"border:none;\n"
"font-weight:300\n"
"}")
        self.headerTitle.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.headerTitle.setObjectName("headerTitle")
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout.addWidget(self.header)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setStyleSheet("background-color: #f8f8ff")
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.central = QtWidgets.QFrame(self.content)
        self.central.setMaximumSize(QtCore.QSize(450, 650))
        self.central.setStyleSheet("background-color: #f8f8ff")
        self.central.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.central.setFrameShadow(QtWidgets.QFrame.Raised)
        self.central.setObjectName("central")
        self.subText = QtWidgets.QTextBrowser(self.central)
        self.subText.setGeometry(QtCore.QRect(120, 10, 221, 41))
        self.subText.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.subText.setStyleSheet("QTextBrowser {\n"
"font-family: \'Roboto\', sans-serif;\n"
"color: #484349;\n"
"font-size: 25px;\n"
"border:none;\n"
"font-weight:300\n"
"}")
        self.subText.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.subText.setObjectName("subText")
        self.btnColorBlack = QtWidgets.QPushButton(self.central)
        self.btnColorBlack.setGeometry(QtCore.QRect(90, 50, 50, 50))
        self.btnColorBlack.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnColorBlack.setStyleSheet("QPushButton {\n"
"background-color: black;\n"
"border: 1px solid black;\n"
"width: 50px;\n"
"height: 50px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 2px solid rgb(255, 85, 85);\n"
"}\n"
"")
        self.btnColorBlack.setText("")
        self.btnColorBlack.setObjectName("btnColorBlack")
        self.btnColorRndm1 = QtWidgets.QPushButton(self.central)
        self.btnColorRndm1.setGeometry(QtCore.QRect(150, 50, 50, 50))
        self.btnColorRndm1.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnColorRndm1.setStyleSheet("QPushButton {\n"
"background-color: none;\n"
"border: 1px solid black;\n"
"width: 50px;\n"
"height: 50px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 2px solid rgb(255, 85, 85);\n"
"}")
        self.btnColorRndm1.setText("")
        self.btnColorRndm1.setObjectName("btnColorRndm1")
        self.btnColorRndm2 = QtWidgets.QPushButton(self.central)
        self.btnColorRndm2.setGeometry(QtCore.QRect(210, 50, 50, 50))
        self.btnColorRndm2.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnColorRndm2.setStyleSheet("QPushButton {\n"
"background-color: none;\n"
"border: 1px solid black\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 2px solid rgb(255, 85, 85);\n"
"}")
        self.btnColorRndm2.setText("")
        self.btnColorRndm2.setObjectName("btnColorRndm2")
        self.btnColorRndm3 = QtWidgets.QPushButton(self.central)
        self.btnColorRndm3.setGeometry(QtCore.QRect(270, 50, 50, 50))
        self.btnColorRndm3.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnColorRndm3.setStyleSheet("QPushButton {\n"
"background-color: none;\n"
"border: 1px solid black\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 2px solid rgb(255, 85, 85);\n"
"}")
        self.btnColorRndm3.setText("")
        self.btnColorRndm3.setObjectName("btnColorRndm3")
        self.btnColorWhite = QtWidgets.QPushButton(self.central)
        self.btnColorWhite.setGeometry(QtCore.QRect(330, 50, 50, 50))
        self.btnColorWhite.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnColorWhite.setStyleSheet("QPushButton {\n"
"background-color: white;\n"
"border: 1px solid black\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 2px solid rgb(255, 85, 85);\n"
"}")
        self.btnColorWhite.setText("")
        self.btnColorWhite.setObjectName("btnColorWhite")
        self.inputBoardSize = QtWidgets.QTextEdit(self.central)
        self.inputBoardSize.setGeometry(QtCore.QRect(70, 120, 251, 31))
        self.inputBoardSize.setStyleSheet("QTextEdit {\n"
"background-color: white;\n"
"color: #484349;\n"
"font-family: \'Roboto\', sans-serif;\n"
"border: 1px solid #484349;\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"border: 3px solid black;\n"
"}\n"
"")
        self.inputBoardSize.setObjectName("inputBoardSize")
        self.btnCreateBoard = QtWidgets.QPushButton(self.central)
        self.btnCreateBoard.setGeometry(QtCore.QRect(310, 110, 61, 51))
        self.btnCreateBoard.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnCreateBoard.setStyleSheet("QPushButton {\n"
"font-family: \'Roboto\', sans-serif;\n"
"margin-right: 3px;\n"
"border: 0;\n"
"padding: 15px;\n"
"color: whitesmoke;\n"
"font-style: italic;\n"
"font-weight: 300;\n"
"background-color: rgb(75, 75, 75);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 2px solid rgb(255, 85, 85);\n"
"}\n"
"")
        self.btnCreateBoard.setObjectName("btnCreateBoard")
        self.btnEraseBoard = QtWidgets.QPushButton(self.central)
        self.btnEraseBoard.setGeometry(QtCore.QRect(370, 110, 71, 51))
        self.btnEraseBoard.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnEraseBoard.setStyleSheet("QPushButton {\n"
"font-family: \'Roboto\', sans-serif;\n"
"margin-right: 3px;\n"
"border: 0;\n"
"padding: 15px;\n"
"color: whitesmoke;\n"
"font-style: italic;\n"
"font-weight: 300;\n"
"background-color: rgb(75, 75, 75);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 2px solid rgb(255, 85, 85);\n"
"}\n"
"")
        self.btnEraseBoard.setObjectName("btnEraseBoard")
        self.btnNewColor = QtWidgets.QPushButton(self.central)
        self.btnNewColor.setGeometry(QtCore.QRect(190, 160, 111, 51))
        self.btnNewColor.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.btnNewColor.setStyleSheet("QPushButton {\n"
"font-family: \'Roboto\', sans-serif;\n"
"margin-right: 3px;\n"
"border: 0;\n"
"padding: 15px;\n"
"color: whitesmoke;\n"
"font-style: italic;\n"
"font-weight: 300;\n"
"background-color: rgb(75, 75, 75);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"border: 2px solid rgb(255, 85, 85);\n"
"}\n"
"")
        self.btnNewColor.setObjectName("btnNewColor")
        self.line = QtWidgets.QFrame(self.central)
        self.line.setGeometry(QtCore.QRect(20, 210, 421, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.board = QtWidgets.QFrame(self.central)
        self.board.setGeometry(QtCore.QRect(125, 235, 200, 200))
        self.board.setMaximumSize(QtCore.QSize(400, 400))
        self.board.setStyleSheet("background-color: #fff;")
        self.board.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.board.setFrameShadow(QtWidgets.QFrame.Raised)
        self.board.setObjectName("board")
        self.line.raise_()
        self.subText.raise_()
        self.btnColorBlack.raise_()
        self.btnColorRndm1.raise_()
        self.btnColorRndm2.raise_()
        self.btnColorRndm3.raise_()
        self.btnColorWhite.raise_()
        self.inputBoardSize.raise_()
        self.btnCreateBoard.raise_()
        self.btnEraseBoard.raise_()
        self.btnNewColor.raise_()
        self.board.raise_()
        self.horizontalLayout.addWidget(self.central)
        self.verticalLayout.addWidget(self.content)
        self.bottom = QtWidgets.QFrame(self.centralwidget)
        self.bottom.setMaximumSize(QtCore.QSize(16777215, 41))
        self.bottom.setStyleSheet("background-color: rgb(75, 75, 75);\n"
"")
        self.bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom.setObjectName("bottom")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.bottom)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.bottom)
        self.frame_2.setMaximumSize(QtCore.QSize(450, 16777215))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_2)
        self.textBrowser.setGeometry(QtCore.QRect(200, 0, 271, 41))
        self.textBrowser.setStyleSheet("QTextBrowser {\n"
"font-family: \'Roboto\', sans-serif;\n"
"color: white;\n"
"font-size: 13px;\n"
"border:none;\n"
"font-weight:300\n"
"}")
        self.textBrowser.setOpenExternalLinks(True)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.bottom)
        self.header.raise_()
        self.bottom.raise_()
        self.content.raise_()
        PaletaDeCores.setCentralWidget(self.centralwidget)

        self.retranslateUi(PaletaDeCores)
        QtCore.QMetaObject.connectSlotsByName(PaletaDeCores)

    def retranslateUi(self, PaletaDeCores):
        _translate = QtCore.QCoreApplication.translate
        PaletaDeCores.setWindowTitle(_translate("PaletaDeCores", "Paleta de Cores"))
        self.headerTitle.setHtml(_translate("PaletaDeCores", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto,sans-serif\'; font-size:35px; font-weight:296; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:35px;\">Paleta de Cores</span></p></body></html>"))
        self.subText.setHtml(_translate("PaletaDeCores", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto,sans-serif\'; font-size:25px; font-weight:296; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:25px;\">Pincéis</span></p></body></html>"))
        self.inputBoardSize.setPlaceholderText(_translate("PaletaDeCores", "Tamanho Máximo: 50"))
        self.btnCreateBoard.setText(_translate("PaletaDeCores", "Criar"))
        self.btnEraseBoard.setText(_translate("PaletaDeCores", "Limpar"))
        self.btnNewColor.setText(_translate("PaletaDeCores", "Novas Cores"))
        self.textBrowser.setHtml(_translate("PaletaDeCores", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto,sans-serif\'; font-size:13px; font-weight:296; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Inter\'; font-size:13pt; font-weight:400;\">Created By: </span><a href=\"https://github.com/marlondlacerda/\"><span style=\" font-family:\'Inter\'; font-size:13pt; font-weight:400; text-decoration: underline; color:#1b6acb;\">Marlon Lacerda</span></a></p></body></html>"))
